export default {
    //歌曲详情
    songDetails:{
        songs:[{
            al:{
                picUrl:'',
            },
            ar:[{
                name:''
            }],
            name:''
        }]
    },
    //音乐歌词
    Lyric:'[00:00:00]歌词加载中！',
    //歌曲当前时间
    musicCurtime:0,
    //音乐url
    musicUrl:'',
    //播放状态
    playStatus:false,
    //歌曲总时长
    musicDuration:0,
    //是否是当前音乐
    curMusic:'',
    //底部播放列表开关
    songListStatus:false

}